// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvkiajchjvqafnyqyavi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2a2lhamNoanZxYWZueXF5YXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTY0MjEsImV4cCI6MjA2MDk3MjQyMX0.CUSInCgIkGjp88i8e6FLIivuhj3lCw0EfF4QU6-LFRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);